# -*- coding: utf-8 -*-
"""1st-programe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/akhilnchandran/e732c2553fb0657092f9d00ee49bdda2/1st-programe.ipynb
"""

my_string = "Hello, World!"
substring = my_string[:5]
print(substring)

my_string = "Python is fun"
substring = my_string[7:9]
print(substring)

my_string = "programming"
substring = my_string[3:7]
print(substring)

my_string = "abcdefgh"
even_index_chars = my_string[0::2]
print(even_index_chars)

my_string = "abcdefgh"
substring = my_string[-4:-1]
print(substring)

my_string = "Data Science"
last_three = my_string[-3:]
print(last_three)

my_string = "abcdefghij"
every_second_character = my_string[::2]
print(every_second_character)

my_string = "1234567890"
odd_digits = my_string[::2]
print(odd_digits)

my_string = "Hello"
reversed_string = my_string[::-1]
print(reversed_string)

my_string = "abcdefghijk"
substring = my_string[::2]
print(substring)